development/config/routes.rb
Rails.application.routes.draw do

  get 'pages/forem'

  mount Forem::Engine, :at => '/forems'

  resources :neighborhoods
  get 'account/account'
  get 'account/join'

  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'home#index'
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :users

end

development/app/models/lead.rb
class Lead < ActiveRecord::Base
  has_many :users

  def create_lead
    
  end

end

development/app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  validates :name, :uniqueness => { message: "There can only be one community with the same name!" }
end

development/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :neighborhood
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable

  def forem_name
      nickname
  end
  acts_as_messageable

  def mailboxer_name
    self.fname
  end

  def mailboxer_email(object)
    self.email
  end
end

development/app/controllers/account_controller.rb
class AccountController < ApplicationController
  def account
  end
end

development/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def forem_user
    current_user
  end
  helper_method :forem_user

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
protect_from_forgery with: :exception
  helper_method :mailbox, :conversation

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end
end

development/app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:notice] = "Your message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user).order("created_at ASC")
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end


  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end


  private

  def conversation_params
    params.require(:conversation).permit(:subject, :body,recipients:[])
  end

  def message_params
    params.require(:message).permit(:body, :subject)
  end
end

development/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

development/app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
  before_action :authenticate_user!

  def inbox
    @inbox = mailbox.inbox
    @active = :inbox
  end

  def sent
    @sent = mailbox.sentbox
    @active = :sent
  end

  def trash
    @trash = mailbox.trash
    @active = :trash
  end
end

development/app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  before_action only: [:show, :edit, :create, :destroy]
  def new
    @neighborhood = Neighborhood.new
    @neighborhoods = Neighborhood.all
  end
  def index
    @neighborhoods = Neighborhood.all
  end
  def create
    @neighborhood = Neighborhood.new(hood_params)
    respond_to do |format|
      if @neighborhood.save
        format.html { redirect_to root_path, notice: "Neighborhood: #{@neighborhood.name} was successfully created." }
        format.json { render :show, status: :created, location: @neighborhood }
      else
        format.html { redirect_to "/neighborhoods/new", notice: "Duplicate neighborhood, try again!" }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def hood_params
    params.require(:neighborhood).permit(:name,:zip)
  end
end

development/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def forum
  end
  
end

development/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:fname, :mname, :lname, :nickname,:address, :city, :zip, :email, :neighborhood_id, :password, :password_confirmation, :current_password)
  end

  def account_update_params
    params.require(:user).permit(:fname, :mname, :lname, :nickname,:address, :city, :zip, :email, :password, :password_confirmation, :current_password)
  end
end

development/app/helpers/account_helper.rb
module AccountHelper
end

development/app/helpers/application_helper.rb
module ApplicationHelper
  def active_page(active_page)
    @active == active_page ? "active" : ""
  end
end

development/app/helpers/conversations_helper.rb
module ConversationsHelper
end

development/app/helpers/home_helper.rb
module HomeHelper
end

development/app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    # how to get the number of unread messages for the current user
    # using mailboxer
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

development/app/helpers/neighborhood_helper.rb
module NeighborhoodHelper
end

development/app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

development/app/helpers/pages_helper.rb
module PagesHelper
end

development/app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="http://placehold.it/64x64" alt="...">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.fname %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    <%= link_to "View", conversation_path(conversation)  %>
  </div>
</div>

development/app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :recipients %>
      <%= f.select(:recipients, User.all.collect {|p| [ p.fname, p.id ] }, {}, { multiple: true , class: "form-control" })%>
    </div>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>

    <%= f.submit "Send Message", class: "btn btn-success" %>

<% end %>

development/app/views/conversations/_messages.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <!-- user avators can go here -->
        <a href="#">
          <img class="media-object" src="http://placehold.it/64x64" alt="...">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.fname %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

development/app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

development/app/views/conversations/show.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<div class="row">
  <div class="spacer"></div>
  <div class="col-md-6">
    <%= link_to "Compose", new_conversation_path, class: "btn btn-success" %>
  </div>
  <div class="col-md-6 text-right">
    <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
    <% else %>
        <%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post,
                    data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="spacer"></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>

development/app/views/forem/admin/categories/_form.html.erb
<%= simple_form_for [forem, :admin, @category] do |f| %>
  <%= f.input :name %>
  <%= f.input :position %>
  <%= f.submit :class => "btn btn-primary" %>
<% end %>

development/app/views/forem/admin/categories/edit.html.erb
<h2><%= t("forem.admin.category.edit", :title => @category.name) %></h2>

<%= render "form" %>

development/app/views/forem/admin/categories/index.html.erb
<h2><%= t("forem.admin.category.index") %></h2>
<%= link_to t('back_to_admin', :scope => "forem.admin"), forem.admin_root_path %><br><br>
<%= link_to t("forem.admin.category.new_link"), forem.new_admin_category_path, :class => "btn btn-primary" %><br><br>

<table id='forums' class='forums table-striped table' cellspacing='0'>
  <thead>
    <tr>
      <th><%= t('edit', :scope => 'forem.admin.categories') %></th>
      <th><%= t('delete', :scope => 'forem.admin.categories') %></th>
      <th><%= t('category', :scope => 'forem.admin.categories') %></th>

    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr class="forum <%= cycle("odd", "even") %>">
        <td><%= link_to t('edit', :scope => 'forem.admin.categories'), forem.edit_admin_category_path(category), :class => "btn btn-info" %></td>
        <td><%= link_to t('delete', :scope => 'forem.admin.categories'), forem.admin_category_path(category), :method => :delete, 
        data: { :confirm => t("delete_confirm", :scope => 'forem.admin.categories') }, :class => "btn btn-danger" %></td>
        <td>
          <%= forem_emojify(category.name) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('forem.admin.forum.index'), forem.admin_forums_path %>

development/app/views/forem/admin/categories/new.html.erb
<h2><%= t('new', :scope => 'forem.admin.category') %></h2>

<%= render "form" %>

development/app/views/forem/admin/groups/_form.html.erb
<%= simple_form_for([forem, :admin, @group]) do |f| %>
  <%= f.input :name %>
  <%= f.submit :class => "btn btn-primary" %>
<% end %>

development/app/views/forem/admin/groups/index.html.erb
<h2><%= t('forem.admin.group.index') %></h2>
<%= link_to t('back_to_admin', :scope => "forem.admin"), forem.admin_root_path %><br><br>
<%= link_to t('forem.admin.group.new'), forem.new_admin_group_path, :class => "btn btn-primary" %>

<table id='groups' class='index table table-striped' cellspacing='0'>
  <thead>
    <tr>
      <th><%= t('edit', :scope => 'forem.admin.groups') %></th>
      <th><%= t('delete', :scope => 'forem.admin.groups') %></th>
      <th><%= t('name', :scope => 'forem.admin.groups') %></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td>
          <%= link_to t('edit', :scope => 'forem.admin.groups'), forem.admin_group_path(group) %>
        </td>
        <td>
          <%= link_to t('delete', :scope => 'forem.admin.groups'), forem.admin_group_path(group), :method => :delete %>
        </td>
        <td>
          <%= link_to forem_emojify(group.name), forem.admin_group_path(group) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

development/app/views/forem/admin/groups/new.html.erb
<h2><%= t("forem.admin.group.new") %></h2>

<%= render "form" %>

development/app/views/forem/admin/groups/show.html.erb
<h2><%= t('forem.admin.group.members', :group => forem_emojify(@group.name)) %></h2>
<%= link_to t('back_to_groups', :scope => "forem.admin"), admin_groups_path %>
<div class="row">
  <h3><%= t('.add_a_new_member') %></h3>
  <%= form_tag add_admin_group_members_url(@group) do %>
    <p>
      <%= text_field_tag "user_id" %>
    </p>
    <p class="col-md-1">
      <%= submit_tag t(".add_member"), :class => "btn btn-primary" %>
    </p>
  <% end %>
</div>

<% if @group.members.any? %>
  <h3><%= t('.current_members') %></h3>
  <div class="row">
    <ul id='members'>
      <% @group.members.each do |member| %>
        <li><%= member.forem_name %> |
          <%= link_to t('forem.admin.groups.show.remove_member'), admin_group_member_url(@group, member),
                      method: :delete, data: { confirm: t('are_you_sure') } %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<script>
  $("#user_id").select2({
    containerCssClass: "col-md-5",
    ajax: {
      url: "<%= forem.admin_user_autocomplete_url %>",
      data: function(term, page) {
        return { "term": term }
      },
      results: function(data, page) {
        return { results: data };
      }
    },
    formatResult: function(result) {
      return result.identifier;
    },
    formatSelection: function(result) {
      return result.identifier;
    }
  });
</script>

development/app/views/forem/admin/topics/_form.html.erb
<%= simple_form_for [forem, :admin, @topic.forum, @topic] do |f| %>
  <%= f.input :subject %>
  <%= f.association :forum , :label => "Forum" %>
  <%= f.label :locked %>
  <%= f.check_box :locked %>
  <%= f.label :pinned %>
  <%= f.check_box :pinned %>
  <%= f.label :hidden %>
  <%= f.check_box :hidden %>

  <br />
  <%= f.submit :class => "btn btn-primary" %>
<% end %>

development/app/views/forem/admin/topics/edit.html.erb
<h2><%= t("forem.topic.edit", :subject => @topic.subject) %></h2>

<%= render "form" %>

development/app/views/forem/categories/_category.html.erb
<% if can?(:read, category) %>
  <div id='category_<%= category.id %>' class='category'>
    <h2><%= link_to forem_emojify(category.name), [forem, category] %></h2>
    <%= render "/forem/forums/listing", :category => category %>
  </div>
<% end %>

development/app/views/forem/categories/show.html.erb
<div class='category'>
  <h2><%= link_to t('forem.forum.forums'), forem.forums_path %> &raquo; <%= link_to forem_emojify(@category), [forem, @category] %></h2>
  <%= render @category %>
</div>

development/app/views/forem/forums/_forum.html.erb
<% if can?(:read, forum) %>
  <tr class="forum <%= cycle("odd", "even") %>">
    <td>
      <%= link_to forem_emojify(forum.title), forem.forum_path(forum), :class => "title" %>
      <div class='description'><%= forem_format(forum.description) %></div>
      <%= t('forem.forums.index.last_post') -%>
      <span class='last_post'>
        <% if last_post = forum.last_post_for(forem_user) -%>
          <%= link_to(forem_emojify(last_post.topic.subject), forem.forum_topic_path(forum, last_post.topic)) -%> <%= t('by') %> <%= last_post.user.forem_name %>
          <time datetime="<%= last_post.created_at.to_s(:db) -%>"><%= "#{time_ago_in_words(last_post.created_at)} #{t("ago")}" %></time>
        <% else %>
          <%= t('forem.forums.index.none') -%>
        <% end %>
      </span>
    </td>
    <td class="topics-count"><%= topics_count(forum) %></td>
    <td class="posts-count"><%= posts_count(forum) %></td>
    <td class="views-count"><%= forum.views_count %></td>
  </tr>
<% end %>

development/app/views/forem/forums/_head.html.erb
<div id='forum'>
  <h2><%= link_to t('forem.forum.forums'), forem.root_path %> &raquo; <%= link_to forem_emojify(forum.category), [forem, forum.category] %> &raquo; <%= link_to forem_emojify(forum.title), [forem, forum] %></h2>
  <span id='description'><%= forem_format(forum.description) %></span>
  <div id='forum_topic_links' class='btn-group'>
    <% unless @topic.try(:new_record?) %>
      <% if can? :create_topic, @forum %>
        <%= link_to t('forem.topic.links.new'), forem.new_forum_topic_path(forum), :class => "btn btn-primary", :id => "new-topic" %>
      <% end %>
    <% end %>
    <% if @topic %>
      <%= link_to t('forem.topic.links.back_to_topics'), forem.forum_path(forum), :class => "btn" %>
    <% end %>
    <% if can? :moderate, @forum %>
      <%= link_to t('forem.forum.moderator_tools'), forem.forum_moderator_tools_path(forum), :class => "btn btn-primary" %>
    <% end %>
  </div>
</div>

development/app/views/forem/forums/_listing.html.erb
<table id='forums' class='forums table table-striped' cellspacing='0'>
  <thead>
  <tr>
    <th class="desc-and-last-post"><%= t('forum', :scope => 'forem.general') %></th>
    <th class="topics-count"><%= t('topics', :scope => 'forem.general') %></th>
    <th class="posts-count"><%= t('posts', :scope => 'forem.general') %></th>
    <th class="views-count"><%= t('forem.forums.index.views') %></th>
  </tr>
  </thead>
  <tbody>
    <%= render category.forums %>
  </tbody>
</table>

development/app/views/forem/forums/index.html.erb
<div id='forums_container'>
  <h1 id='forums_title'><%= t('.title') %></h1>

  <%= render @categories %>
</div>

<br>
<footer id='admin_link'>
  <% if forem_admin? %>
    <%= link_to t("area", :scope => "forem.admin"), forem.admin_root_path %>
  <% end %>
</footer>

development/app/views/forem/forums/show.html.erb
<div class='forum'>
  <%= render :partial => 'forem/forums/head', :locals => { :forum => @forum } %>

  <%= forem_pages_widget(@topics) %>
  <table class='topics table-striped table' cellspacing='0'>
    <col width="80%">
    <col width="10%">
    <col width="10%">
    <thead>
      <tr>
        <!--th class="icon"></th-->
        <th class="byline"><%= t('forem.topic.headings.topic') -%></th>
        <!--th class="latest-post text-center"><%= t('forem.topic.headings.latest') -%></th-->
        <th class="posts-count text-center"><%= t('forem.topic.headings.posts') -%></th>
        <th class="views-count text-center"><%= t('forem.topic.headings.views') -%></th>
      </tr>
    </thead>
    <tbody>
      <% if @topics.empty? %>
        <tr><td colspan='3' align='center'><%= t('forem.topic.none') %></td></tr>
      <% end %>
      <%= render @topics %>
    </tbody>
  </table>
  <%= forem_pages_widget(@topics) %>
</div>

development/app/views/forem/moderation/_options.html.erb
<p>
  <%= f.radio_button "moderation_option", "approve" %>
  <%= f.label "moderation_option_approve", t('approve', :scope => 'forem.posts.moderation'), :class => "label label-success" %>
</p>
<p>
  <%= f.radio_button "moderation_option", "spam" %>
  <%= f.label "moderation_option_spam", t('spam', :scope => 'forem.posts.moderation'), :class => "label label-danger" %>
</p>
<br>
<%= f.submit t('moderate', :scope => 'forem.posts.moderation'), :class => "btn btn-primary" %>

development/app/views/forem/moderation/index.html.erb
<h2><%= t('.title', :forum => forum) %></h2>

<h3><%= t('posts_count', :count => @posts.count, :scope => 'forem.general') %></h3>

<%= form_tag forem.forum_moderate_posts_url(forum), :method => :put do %>
  <div id='posts'>
    <% @posts.limit(25).group_by(&:topic).each do |topic, posts| %>
      <h4><%= forem_emojify(topic.forum.title) %> &raquo; <%= forem_emojify(topic.subject) %></h4>
      <%= render posts, :mass_moderation => true %>
    <% end %>
  </div>
<% end %>

<h3><%= t('topics_count', :count => @topics.count, :scope => 'forem.forum') %></h3>

<div id='topics'>
  <% @topics.limit(25).each_with_index do |topic, topic_counter| %>
    <div id='topic_<%= topic_counter + 1 %>' class='topic <%= cycle('odd', 'even', name: 'topics') -%>'>
      <div class='moderation alert'>
        <%= link_to forem_emojify(topic.subject),
                    forem.forum_topic_path(forum, topic) %>
      </div>
    </div>
  <% end %>
</div>

development/app/views/home/index.html.erb
<div class="alert" id="post1">
  <h2>Welcome to Gazebo</h2>
  <a href="#" onclick="document.getElementById('post1').className = 'none';" class="alertClose">x</a>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi facilisis odio et urna commodo, et rhoncus justo euismod. Phasellus ultrices sapien mi. Integer et dictum lectus. Pellentesque purus tellus, tempus ut posuere ac, pretium sit amet enim. Phasellus non laoreet augue. Quisque accumsan id arcu ultrices scelerisque. Vestibulum sed nibh egestas, fermentum nisi ultrices, mollis ante. Maecenas rutrum enim eu elementum feugiat. Vestibulum at purus tincidunt, condimentum risus vel, tempus magna. Suspendisse posuere tincidunt dictum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer maximus purus quis dignissim tincidunt. Nullam elit metus, sodales et tempor in, posuere ac mauris.
  </p>
  <p>
    Nunc blandit sagittis massa, eu tempus ante maximus in. Ut lorem augue, aliquet nec felis eget, accumsan auctor lectus. Donec malesuada eu odio nec rutrum. Maecenas mattis neque erat, ut tincidunt lorem vehicula et. Nulla vitae mauris vitae mauris dignissim varius. Sed et viverra neque, in luctus leo. Praesent interdum enim metus, ullamcorper viverra eros gravida eget. Aenean ultricies lorem nec tortor ultrices rutrum. Duis gravida justo vel tellus ullamcorper malesuada. Aliquam erat volutpat. Cras blandit purus non dolor auctor scelerisque. Integer bibendum lacus pulvinar euismod porta.
  </p>
  <div class="footer">
    <%= Time.now %>
    <a href="#" id="alertPoster">John Davis</a>
  </div>
</div>

development/app/views/mailbox/_folder_view.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-12">
    <!-- we'll configure this to compose new conversations later -->
      <%= link_to "Compose", new_conversation_path, class: "btn btn-success" %>
    <div class="spacer"></div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <% if is_conversation %>
          <%= render 'conversations/form' %>
        <% else %>
          <%= render partial: 'conversations/conversation', collection: messages %>
        <% end %>
      </div>
    </div>
  </div>

</div>

development/app/views/mailbox/_folders.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<ul class="">
  <li class="<%= active_page(:inbox) %>">
    <%= link_to mailbox_inbox_path do  %>
        <span class="label label-danger pull-right"><%=unread_messages_count%></span>
        <em class=""></em>
        <span>Inbox</span>
    <% end %>
  </li>
  <li class="<%= active_page(:sent) %>">
    <%= link_to mailbox_sent_path do %>

        <em class=""></em>
        <span>Sent</span>
    <% end %>
  </li>

  <li class="<%= active_page(:trash) %>">
    <%= link_to mailbox_trash_path do %>
        <em class=""></em>
        <span>Trash</span>
    <% end %>
  </li>
</ul>

development/app/views/mailbox/inbox.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox } %>

development/app/views/mailbox/sent.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent } %>

development/app/views/mailbox/trash.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @trash } %>

development/app/views/neighborhoods/new.html.erb
<h2>Create a Neighborhood</h2>

<% if notice %>
  <p class='notice'><%= notice %></p>
<% end %>
<%= form_for @neighborhood do |f| %>
<div class="form-group">
  <%= f.label :Neighborhood_Name %><br/>
  <%= f.text_field :name, class: 'form-control', autofocus: true  %>
</div>
<div class="form-group">
  <%= f.label :Zip %><br/>
  <%= f.text_field :zip, class: 'form-control' %>
</div>
</br>
<div class="actions">
  <%= f.submit "Create Neighborhood" %>
</div>
<% end %>